### PR TITLE
Add Anthropic Claude 2.1 model variable

### PR DESCRIPTION
**Pull request by smithakolan**

### CODE REVIEW

**Comment by armandobelardo** [comment]
Hi there @smithakolan! This change is also included within https://github.com/AssemblyAI/assemblyai-java-sdk/pull/53/files, shall we just review #53?

**Comment by Swimburger** [comment]
> Hi there @smithakolan! This change is also included within https://github.com/AssemblyAI/assemblyai-java-sdk/pull/53/files, shall we just review #53?

Yes, we should. The referenced PR is based on the updated OpenAPI spec.
Unfortunately, the change is a breaking change because the allowed type specified in OpenAPI is now the enum or any string.
@dsinghvi was going to look into how we can generate the updated spec in a backwards compatible way.

**Comment by smithakolan** [comment]
@armandobelardo Got it! Closing this PR.

@Swimburger curious as to what caused the change in the spec? Does this affect the way the other models are defined?

**Comment by Swimburger** [comment]
> @Swimburger curious as to what caused the change in the spec? Does this affect the way the other models are defined?

The spec used to specify only the enum of known strings.
Before the holiday, it was decided we should allow any string as well, so now it's defined as the enum of known strings, or any string.

**Pull request closed without merging**
